name: "i2c Garage"
description: "Simple interface to i2c to open my garage via mqtt"
version: "3.0.3"
slug: "i2c-garage"
init: false
# Full access is required to interact with i2c devices
full_access: true
# We use Supervisor API to get MQTT information
# See: https://developers.home-assistant.io/docs/add-ons/communication/#services-api
hassio_api: true
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
